In [ ]:
#variable
a = 10
print(" I am ",a,"years old")

 I am  10 years old


In [ ]:
#adding two int variables
a=int(input("Enter a number: "));
b=int(input("Enter another number: "));
c=a+b;
print("Addition is",c)
print("Subtracton is",a-b)
print("Product is",a*b)
print("Division is",a/b)
print("Remainder is",a%b)
print("Power of a to the b is",a**b)
print("Floor division  is",a//b)



Enter a number: 87
Enter another number: 89
Addition is 176
Subtracton is -2
Product is 7743
Division is 0.9775280898876404
Remainder is 87
Power of a to the b is 41420323172887136317090775242992936475770796498047502858229021582473014613526597928360296793410319531028123733525957305462754476185238404911054531704443764438196755277867927
Floor division  is 0


In [ ]:
#take salary from the user,if the salary is more than 50000 there is a 10% tax deduction print his final salary
sal = int(input("Enter your salary: "))
if (sal>=50000):
    n=sal-(10*sal)/100
    print("The  user salary is",n)
else:
   print("There is no tax for the user.Salary=",sal)




Enter your salary: 15000
There is no tax for the user.Salary= 15000


In [ ]:
#get the salary from the user if the salary is more than or equal to 50000,apply 10% salary deduction,if the salary is less than 50000 apply 5% tax,if the salary is more than 70000,apply 12% tax,if the exceeds 100000 print you are promoted to next level
a = int(input("Enter your salary of the user :"))
if (a<50000):
    n=a-(5*a)/100
    print("The user salary is",n)
elif(a<70000):
    n=a-(10*a)/100
    print("The user salary is",n)
elif(a<100000):
    n=a-(12*a)/100
    print("The user salary is",n)
else:
    print("You ae promoted...")



Enter your salary of the user :75000
The user salary is 66000.0


In [ ]:
for i in range(1, 11):
    print(i)


1
2
3
4
5
6
7
8
9
10


In [ ]:
n = int(input("Enter a number "))
for i in range(1, 11):
    p = n * i
    print(n,'x',i,' = ',p)


Enter a number 15
15 x 1  =  15
15 x 2  =  30
15 x 3  =  45
15 x 4  =  60
15 x 5  =  75
15 x 6  =  90
15 x 7  =  105
15 x 8  =  120
15 x 9  =  135
15 x 10  =  150


In [ ]:
n = int(input("Enter a number: "))
i = 1
while (i<=10):
    p = n * i
    print(n, 'x', i, ' = ', p)
    i = i+1


Enter a number: 20
20 x 1  =  20
20 x 2  =  40
20 x 3  =  60
20 x 4  =  80
20 x 5  =  100
20 x 6  =  120
20 x 7  =  140
20 x 8  =  160
20 x 9  =  180
20 x 10  =  200


In [ ]:
#create a heterogeneous list
l1 = [1,'String',31,50,11]
print(l1)
l1.append("string2")#adds element to back of list
print(l1)
l1.insert(2,'89')
print(l1)

[1, 'String', 31, 50, 11]
[1, 'String', 31, 50, 11, 'string2']
[1, 'String', '89', 31, 50, 11, 'string2']


In [ ]:
l2=["popoye"]
l1.extend(l2)#l1+l2
print(l1)

[1, 'String', '89', 31, 50, 11, 'string2', 'popoye']


In [ ]:
l1.pop(5)
print(l1)

[1, 'String', '89', 31, 50, 'string2', 'popoye']


In [ ]:
l2=["berry"]
#list1.extend(list2)#l1+l2
l1.extend(l2)#l1=l1+l2
print(l1)

[1, 'String', '89', 31, 50, 'string2', 'popoye', 'popoye', 'berry']


In [ ]:
l1.remove('89')#removes an element
l1.pop(5)#removes the index element
print(l1)

[1, 'String', 31, 50, 'string2', 'popoye', 'berry']


In [ ]:
l1.clear()#clears the elements in the list
print(l1)

[]


In [ ]:
#create a list of integers  i need 10 elements,print their squares,save these squares in a new list
l1 = [23,67,12,34,69]
l2 = []
for i in l1:
  l2.append(i*i)
print(l2)
#lc
#newlist = [output for]


[529, 4489, 144, 1156, 4761]


In [ ]:
l1 = [23, 67, 12, 34, 69]
l2 = []
for i in l1:
    if i > 50:
        l2.append(i * i)
print(l2)


[4489, 4761]


In [ ]:
#LC
#newlist =[(st of if) if (cond) else (st of else) for ]
l1=[23,67,12,34,69]
l2=[i*i if (i>50) else 'x' for i in l1]
print(l2)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#Take the salary from the user,if salary  is less than 50000,10% tax,otherwise 15%tax
l1=[250000,12000,30000,55000]
l2=[n-(n*10/100) if(n<50000) else n-(n*15/100) for n in l1]
print(l2)

[212500.0, 10800.0, 27000.0, 46750.0]


In [ ]:
#create
dict1 = {'mentor':'jwalitha','word':'Hello'}
print(dict1['word'])

Hello


In [ ]:
dict3 = {"Dept": "CSE", "details": {"year": "II", "Sec": "D", "Count": 71}}
print("Year is", dict3["details"]["year"])
print("Section is", dict3["details"]["Sec"])
print("Count is", dict3["details"]["Count"])


Year is II
Section is D
Count is 71


In [ ]:
id1 = {34, 56, 78, 39, 100}
names = ["joe", "Suji", "Rohini", "Shankar", "Mani"]
new_zip = zip(id1, names)
result_list = list(new_zip)
print(result_list)


[(34, 'joe'), (100, 'Suji'), (39, 'Rohini'), (56, 'Shankar'), (78, 'Mani')]


Numpy

In [31]:
import numpy as np
A = np.array([[1,2,3,4]]) #1d array
print(A.ndim)
print(A.shape)





2
(1, 4)


In [35]:
import numpy as np #2d array
B=np.array([[1,2,3],[4,5,6]])
#elements in each row = columns
print(B.ndim)
print(B.shape)
print(B)

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [47]:
#3-dimensional
import numpy as np
C=np.array([[[1,2,3,4],[2,3,4,7],],[[1,2,3,4],[2,3,4,7]]])
print(C)
print(C.ndim)
print(C.shape)

[[[1 2 3 4]
  [2 3 4 7]]

 [[1 2 3 4]
  [2 3 4 7]]]
3
(2, 2, 4)


In [49]:
import numpy as np
C = np.zeros((2,4,3))
print(C)
print(C.ndim)
print(C.shape)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
(2, 4, 3)


In [50]:
A = np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [56]:
A = np.arange(1,10,2) #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [61]:
#print all the numbers that are divisible by 8 using arange function betweeen 1 and 100
A = np.arange(8,1001,8) #start,stop,step
print(A)
print(type(A))


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [65]:
#splitting a range into n numbers having common differences
A = np.linspace(48,59,10)
print(A)

[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


In [ ]:
# create a collab file and study tuple and sets