In [ ]:
#variable
a=10
print("I am", a ,"years old")

I am 10 years old


In [ ]:
#adding two integers
a=int(input("Enter a:"))
b=int (input("Enter b:"))
print("sum",a+b )

Enter a:12
Enter b:12
sum 24


In [ ]:
a=int(input("Enter a:"))
print(a)

Enter a:4
4


In [ ]:
#subtracting two integer variables
a=int(input("Enter a:"))
b=int (input("Enter b:"))
print("difference",a-b )

Enter a:12
Enter b:39
difference -27


In [ ]:
#Arthemetic operators
a=int(input("Enter a:"))
b=int (input("Enter b:"))
print("sum:",a+b)
print("difference:9",a-b )
print("product:",a*b )
print("quotient:",a/b )
print("remainder:",a%b )
print("power:",pow(a,b) )
print("floor division:",a//b)Enter a:12


Enter a:12
Enter b:90
sum: 102
difference: -78
product: 1080
quotient: 0.13333333333333333
remainder: 12
power: 13375565248934352031245861515653274879560267436972842215671280963977858996049651078858079966593024
floor division: 0


In [ ]:
#Take salary from the user.If the salary is more than 50000,there is a 10% tax then print hhis final salary.
sal=int(input("Enter the salary:"))
if(sal>=50000):
  sal=sal-(sal*(10/100))
  print(sal)
else:
  print("Your salary is below 50000")

Enter the salary:89000
80100.0


In [ ]:
#Get the salary from the user if the salary is >= 50000 apply 10% deduction if the salary is less than 50000, apply 5% tax.if the salary is more than 70000,apply 12%tax . If the salary exeecds 1L,print you are promoted to next level
sal=int(input("Enter the salary:"))
if(sal<=50000):
  sal=sal-(sal*(5/100))
  print(sal)
elif(sal>50000 and sal<=70000):
  sal=sal-(sal*(10/100))
  print(sal)b
elif(sal>70000 and sal<=1000000):
  sal=sal-(sal*(12/100))
  print(sal)
else:
  print("You got promotion!")



Enter the salary:78000
68640.0


In [ ]:
#multiplication table by for loop
a=range(1,11)
n= int(input("Enter number"))
for i in  a :
  print(n," X ", i ,"=" ,n*i)


Enter number7385
7385  X  1 = 7385
7385  X  2 = 14770
7385  X  3 = 22155
7385  X  4 = 29540
7385  X  5 = 36925
7385  X  6 = 44310
7385  X  7 = 51695
7385  X  8 = 59080
7385  X  9 = 66465
7385  X  10 = 73850


In [ ]:
#Multiplication table based on while loop
n=int(input("Enter a number:"))
i=1
while(i<11):
  print(n," X ", i ,"=" ,n*i)
  i=i+1



Enter a number:34
34  X  1 = 34
34  X  2 = 68
34  X  3 = 102
34  X  4 = 136
34  X  5 = 170
34  X  6 = 204
34  X  7 = 238
34  X  8 = 272
34  X  9 = 306
34  X  10 = 340


In [ ]:
#printing elements from the list
a=["mikasa",6,90.0,True]
for i in a:
  print(i)

mikasa
6
90.0
True


In [ ]:
#mutable
a.append("Appended")#adds elements at back of the list
print(a)
a.insert(4,"hai")#adds the element at the given index position
print(a)

['mikasa', 6, 90.0, True, 'hai', 'Appended', 'Appended', 'Appended']
['mikasa', 6, 90.0, True, 'hai', 'hai', 'Appended', 'Appended', 'Appended']


In [ ]:
l=['armin','eren','mikasa']
l1=[2,'python']
l.extend(l1) #l=l+l1
#list1.extend(list2)
print(l)


['armin', 'eren', 'mikasa', 2, 'python']


In [ ]:
b=["moyemoye",67,90.0,"true",True]
print(a+b)#combines two lists



['mikasa', 6, 90.0, True, 'hai', 'hai', 'Appended', 'Appended', 'Appended', 'moyemoye', 67, 90.0, 'true', True]
['moyemoye', 90.0, 'true', True]
['moyemoye', 90.0, True]


In [ ]:
b=["moyemoye",67,90.0,"true",True]
b.remove(67)#removes the element from the list
print(b)
b.pop(2)#removes the element in the based on the index given
print(b)


['moyemoye', 90.0, 'true', True]
['moyemoye', 90.0, True]


In [ ]:
#clears the list
a.clear()
print(a)

[]


In [ ]:
#Create a list of 10 random integers,and print their squares save these squares in a new list
l=[12,10,4,8,7,90,78,6,3,77]
b=[]
for i in l:
  b.append(i*i)
print(b)

[144, 100, 16, 64, 49, 8100, 6084, 36, 9, 5929]


In [ ]:
#LC
#newlist=[outputcondition forloop]
l=[12,10,4,8,7,90,78,6,3,77]
res=[i*i for i in l]
print(res)

[144, 100, 16, 64, 49, 8100, 6084, 36, 9, 5929]


In [ ]:
#lc
l=[12,10,4,8,7,90,78,6,3,77]
res=[i*i for i in l if i>50]
print(res)


[8100, 6084, 5929]


In [ ]:
#lc
#newlist=[(st of if) if (cond)else(st of else) for]
l=[12,10,4,8,7,90,78,6,3,77]
res=[i*i  if i >50  else 'X' for i in l ]
print(res)


['X', 'X', 'X', 'X', 'X', 8100, 6084, 'X', 'X', 5929]


In [ ]:
a=[3,1,6,9]
a.sort()
print(a)

[1, 3, 6, 9]


In [ ]:
a=(12,89,5,3,0)
b=sorted(a)
print(b)
print(a)

[0, 3, 5, 12, 89]
(12, 89, 5, 3, 0)


In [ ]:
#Take the salary from the user if the salary is les than 50k,10% tax otherwise 15% tax
sal=int(input("Enter salary:"))

res=[sal-(sal*10/100) if (sal < 50000) else sal-(sal*15/100)]
print(res)


Enter salary:60000
[51000.0]


In [ ]:
sal=[34000,89000,60000,78000]
res=[i-(i*10/100) if (i < 50000) else i-(i*15/100) for i in sal]
print(res)



[30600.0, 75650.0, 51000.0, 66300.0]


In [ ]:
#create a dictionary
dict1={"Mentor":'Jwalitha',1:"Yajnica",2:'Eren',3:"Mikasa"}
print(dict1)

{'Mentor': 'Jwalitha', 1: 'Yajnica', 2: 'Eren', 3: 'Mikasa'}


In [ ]:
#create a dictionary
dict1={"Mentor":'Jwalitha',"Mentor":"Yajnica",2:'Eren',3:"Mikasa"}
print(dict1)

{'Mentor': 'Yajnica', 2: 'Eren', 3: 'Mikasa'}


In [ ]:
#to print keys and values
print(dict1.keys())
print(dict1.values())

dict_keys(['Mentor', 2, 3])
dict_values(['Yajnica', 'Eren', 'Mikasa'])


In [ ]:
#to access value using a key
print(dict1[3])


Mikasa


In [ ]:
#nested dictionary
dict2={"Dept":"CSE","details":{"year":2,"Sec":"D","count":71}}
print( "year is", dict2["details"]["year"])
print( "section is", dict2["details"]["Sec"])
print( "Strength is" ,dict2["details"]["count"])

year is 2
section is D
Strength is 71


In [ ]:
dict2={"Dept":"CSE","details":{"year":2,"Sec":"D","count":71}}
print(dict2["details"]["year","Sec",])

In [ ]:
#to create a dictionary using two lists
l=[34,78,19,80,10]
m=["mikasa",'eren',"mikey","suzume","hina"]
new_zip=(zip(l,m))
for i in new_zip:
  print(i)

(34, 'mikasa')
(78, 'eren')
(19, 'mikey')
(80, 'suzume')
(10, 'hina')


In [ ]:
l=[34,78,19,80,10]
m=["mikasa",'eren',"mikey","suzume","hina"]
new_zip=(zip(l,m))

print(dict(new_zip))

{34: 'mikasa', 78: 'eren', 19: 'mikey', 80: 'suzume', 10: 'hina'}


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.ndim)
print(A.shape)
print(A)

1
(4,)
[1 2 3 4]


In [ ]:
#creating 2-d array
D=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#elements in each row=coloumns
print(D.ndim)
print(D.shape)
print(D)

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#3-d array
import numpy as np
B=np.array([[[1,2,3,4],[3,7,8,9]],[[5,6,7,8],[9,10,1,12]]])
#no of elements=group*rows*coloumns
print(B.ndim)
print(B.shape)#(group,rows,coloumns)
print(B)

3
(2, 2, 4)
[[[ 1  2  3  4]
  [ 3  7  8  9]]

 [[ 5  6  7  8]
  [ 9 10  1 12]]]


In [ ]:
#fills the matrix with one's
C=np.ones((2,3))
print(C)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
S=np.ones(((2,3,4)))
print(S)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
Q=np.zeros((2,5))
print(Q)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
Q=np.zeros(((2,5,8)))
print(Q)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
r=np.eye(3)
print(r)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
A=np.arange(1,10,2)
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using a range function between 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
A=np.linspace(8,3,10)#splitting a range into n numbers with common differences
print(A)

[8.         7.44444444 6.88888889 6.33333333 5.77777778 5.22222222
 4.66666667 4.11111111 3.55555556 3.        ]


In [ ]:
#creating a tuple
A_tuple = (0, [1, 2, 3], (4, 5, 6), 7.0)
print(A_tuple)

(0, [1, 2, 3], (4, 5, 6), 7.0)


In [ ]:
#accesing the elements from tuple
print('The first element:', A_tuple[0])
print('The last element:', A_tuple[-1])
print('The data type of the second element:', type(A_tuple[1]))

The first element: 0
The last element: 7.0
The data type of the second element: <class 'list'>


In [ ]:
print(A_tuple[2][1])

5


In [ ]:
#accesing with  +veindexes
tuplea = 2, 4, 5, 7, 8, 10
print(tuplea[:3])
print(tuplea[4:])


(2, 4, 5)
(8, 10)


In [ ]:
#accessing elements with -ve indexing
print(tuplea[-3:])
print(tuplea[2:5])

In [ ]:
#concatnating two tuples
tuple_1 = (1, 2)
tuple_2 = (3, 4)
print(tuple_1 + tuple_2)

(1, 2, 3, 4)


In [ ]:
#duplicating the tuples
my_tuple = (1, 7, 9, 8)
print(my_tuple * 2)

(1, 7, 9, 8, 1, 7, 9, 8)


In [ ]:
#zipping two tuples
b = ('eren', 'mikasa', 'armin', 'sasha')
a = ('mikey', 'hina', 'suzume', 'satoru')
z = zip(b, a)
l=tuple(z)
print(l)

(('eren', 'mikey'), ('mikasa', 'hina'), ('armin', 'suzume'), ('sasha', 'satoru'))


In [ ]:
#making a tuple
thistuple = tuple(("apple", "banana", "cherry"))
print(thistuple)

('apple', 'banana', 'cherry')


In [ ]:
#length of the tuple
thistuple = ("apple", "banana", "cherry")
print(len(thistuple))

3


In [ ]:
#creating a set
thisset = {"mikasa", "kaneki", "eren"}
print(thisset)

{'mikasa', 'kaneki', 'eren'}


In [ ]:
#length of the set
thisset = {"mikasa", "kaneki", "eren"}
print(len(thisset))

3


In [ ]:
#type of the set
thisset = {"mikasa", "kaneki", "eren"}
print(type(thisset))

In [ ]:
#making a tuple into set
thisset = set(("mikasa", "kaneki", "eren"))
print(thisset)

{'eren', 'kaneki', 'mikasa'}


In [ ]:
#union
set1 = {11, 22, 33}
set2 = {33, 54, 75}
union_set = set1 | set2
print(union_set)

{33, 22, 54, 75, 11}


In [ ]:
#intersection
set1 = {11, 22, 33}
set2 = {33, 54, 75}
intersection_set = set1 & set2
print(intersection_set)

{33}


In [ ]:
#difference
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}
set3 = set1.difference(set2)
print(set3)
set4 = set1 - set2
print(set4)

{1, 2}
{1, 2}


In [ ]:
#checks whether subset or not
set1 = {1, 2, 3, 4, 5}
set2 = {2, 4}
print(set2.issubset(set1))
print(set1.issubset(set2))

In [ ]:
#deleting element from the set
set1 = {1, 2, 3, 4, 5}
set1.discard(2)
print(set1)

{1, 3, 4, 5}


In [ ]:
#study tuples and sets and create a collab note
#documentation