In [ ]:
a =[8,6,7,12,3,5]
b =sorted(a)
print(b)

[3, 5, 6, 7, 8, 12]


In [ ]:
a =[8,6,7,12,3,5]
b =sorted(a)
print(a)
print(b)

[8, 6, 7, 12, 3, 5]
[3, 5, 6, 7, 8, 12]


In [ ]:
import numpy as np


In [ ]:
A =np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A = np.linspace(2,8, 10).reshape(5, 2)
print(A)


[[2.         2.66666667]
 [3.33333333 4.        ]
 [4.66666667 5.33333333]
 [6.         6.66666667]
 [7.33333333 8.        ]]


In [ ]:
B = np.array([45,67,89,12,34,51,98,98]).reshape(2,2,2)
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [98 98]]]


In [ ]:
B = np.array([45,67,89,12,34,51,98,98])
B.resize(2,2,2)#change the shape of original array
#reshape - changes needs saving in another variable
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [98 98]]]


In [ ]:
A = np.array([34,56,78,90])
B = np.array([7,9,3,12])#list will throw an error while arrays iterate themselves
C = A-B
print(C)

[27 47 75 78]


In [ ]:
A = np.array([34,56,78,90])
B = np.array([34,56,78,90])#list will throw an error while arrays iterate themselves
C = A+B
print(C)

[ 68 112 156 180]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
C =A*B
print(C)

[[1156 3136]
 [6084 8100]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
C = A*B #one on one multiplication
print("_______________________________")
print(C)


[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
_______________________________
[[1156 3136]
 [6084 8100]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
C = A*B #one on one multiplication
print("_______________________________")
print(C)


[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
_______________________________
[[1156 3136]
 [6084 8100]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
C = A@B #one on one multiplication
print("_______________________________")
print(C)


[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
_______________________________
[[ 5524  6944]
 [ 9672 12468]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
C = A.dot(B) #one on one multiplication
print("_______________________________")
print(C)

[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
_______________________________
[[ 5524  6944]
 [ 9672 12468]]


In [ ]:
 A = np.array([34.2,56.7,78.2,90.9,90.8])#integers
 print(A.max())
 print(A.min())

90.9
34.2


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(A.max(axis=0)) #axis 0-column
print("_______________________________")
print(A.max(axis=1)) #axis 1-row


print(B)

[[34 56]
 [78 90]]
_______________________________
[78 90]
_______________________________
[56 90]
[[34 56]
 [78 90]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(A.min(axis=0)) #axis 0-column
print("_______________________________")
print(A.min(axis=1)) #axis 1-row

[[34 56]
 [78 90]]
_______________________________
[34 56]
_______________________________
[34 78]


In [ ]:
#joining arrays
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
print("After vertically stacking the arrays")
print(np.vstack((A,B)))

[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
After vertically stacking the arrays
[[34 56]
 [78 90]
 [34 56]
 [78 90]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
print("After horizontally stacking the arrays")
print(np.hstack((A,B)))

[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
After horizontally stacking the arrays
[[34 56 34 56]
 [78 90 78 90]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
print("After horizontally stacking the arrays")
print(np.stack((A,B)))

[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
After horizontally stacking the arrays
[[[34 56]
  [78 90]]

 [[34 56]
  [78 90]]]


In [ ]:
A =np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack((A))) #no of rows --> no of groups
#no of col in every group --> no of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([34,56,78,90]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
print("After horizontally stacking the arrays")
print(np.stack((A,B)))

[[34 56]
 [78 90]]
_______________________________
[[34 56]
 [78 90]]
After  dstacking the arrays
[[[34 34]
  [56 56]]

 [[78 78]
  [90 90]]]


In [ ]:
#spliting
A =np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
A =np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.hsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
A =np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
A =np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
A = np.linspace(17, 4, 12).reshape(3, 4)
print(A)
print(A.argmax())


[[17.         15.81818182 14.63636364 13.45454545]
 [12.27272727 11.09090909  9.90909091  8.72727273]
 [ 7.54545455  6.36363636  5.18181818  4.        ]]
0


In [ ]:
A = np.array([17, 4, 18, 56, 33, 50, 21, 11, 13, 22, 34, 46]).reshape(3, 4)
print(A)
print(A.argmax(axis=0)) #[0 0 0 0]
                       #  1 1 1 1


[[17  4 18 56]
 [33 50 21 11]
 [13 22 34 46]]
[1 1 2 0]


In [ ]:
A = np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3, 4)
print(A)
print(A.argmax(axis=1)) #position [0 1 2 3]
                                  #   0 1 2

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[3 2 1]


Statistics

In [ ]:
#mean,median,std,var
A =np.array([12,34,25,66,71,88])
print("Mean",np.mean(A))
print("Median",np.median(A))
print("Variance",np.var(A))
print("Standard dev",np.std(A))

Mean 49.333333333333336
Median 50.0
Variance 743.888888888889
Standard dev 27.274326552435515


Trigonometry

In [ ]:
A = np.pi #pi=180
print(A) #radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B =np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
C =np.array([30,45,60,90,120,180])
print(np.deg2rad(C))

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265]


In [ ]:
C =np.array([0,30,45,60,90,120,180])
D= np.deg2rad(C)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
1/np.cos(C)

array([ 1.        ,  6.48292123,  1.90359441, -1.04996469, -2.23177613,
        1.22822817, -1.67095526])

In [ ]:
np.arctan(1)

0.7853981633974483

In [ ]:
a = 6
b = 4
print(np.hypot(a,b)) #hypotnuese


7.211102550927978


Searching!

In [ ]:
A = np.array([98,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A = np.array([98,3,45,21,34,90,21])
print(np.where(A%2)) #even

(array([1, 2, 3, 6]),)


In [ ]:
A = np.array([98,3,45,21,34,90,21])
print(np.where(A>25)) #greater than 25

(array([0, 2, 4, 5]),)


In [1]:
import numpy as np

In [8]:
A=np.array([90,3,45,21,34,90,21])
print(np.searchsorted(A,21))

2


Linear algebra and Ufunc

In [9]:
import numpy as np


In [15]:
a =np.array([6,34,2,67,8])
b =np.array([5,12,4,1,3])
print(np.add(a,b))
print(np.divide(a,b))
print(np.subtract(a,b))
print(np.divmod(a,b))
print(np.add(a,b))



[11 46  6 68 11]
[ 1.2         2.83333333  0.5        67.          2.66666667]
[ 1 22 -2 66  5]
(array([ 1,  2,  0, 67,  2]), array([ 1, 10,  2,  0,  2]))
[11 46  6 68 11]


In [17]:
a =np.array([6,34,2,67,8])
b =np.array([5,12,4,1,3])
print(np.setdiff1d(a,b))

[ 2  6  8 34 67]


In [19]:
a =np.array([6,24,60,12,18])
b =np.array([6,4,10,5,4])
print(np.intersect1d(a,b))

[6]


In [20]:
#rounding
al=np.trunc([-3.1666,3.1667])
print(al)

[-3.  3.]


In [21]:
al=np.around([-3.1666,4])
print(al)

[-3.  4.]


In [22]:
al=np.fix([-3.1666,3.1667])
print(al)

[-3.  3.]


In [23]:
al=np.floor([-3.1666,3.1667])
print(al)

[-4.  3.]


In [24]:
al=np.ceil([-3.1666,3.1667])
print(al)

[-3.  4.]


In [25]:
A = np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [26]:
A = np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [29]:
np.lcm(445,355)

31595

In [28]:
np.gcd(34,56)


2

In [30]:
print(np.lcm(445,355))
print(np.gcd(445,355))

31595
5


In [32]:
Ar = np.array([45,65,30])
print(np.lcm.reduce(Ar))

1170


In [34]:
Ar = np.array([45,65,30])
print(np.lcm.reduce(Ar))
print(np.gcd.reduce(Ar))

1170
5


In [36]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [44]:
import random as rd
A = rd.random()
print(A)

0.16851110200011243


In [53]:
A= rd.randint(1,4)
print(A)

4


In [62]:
import random as rd
a =np.array([1,2,3])
b =np.array([4,5,6])
print(np.inner(a,b))

32


In [58]:
  A =np.array([2,3])
  B =np.array([4,5,6])
  print(np.cross(A,B))

[ 18 -12  -2]
